objects = t
CC = /usr/local/gcc-4.8.2/bin/gcc
CXX = /usr/local/gcc-4.8.2/bin/g++
CFLAGS = 
CXXFLAGS = -std=c++11
all: $(objects)
t: UniquePtrTest.cpp
	$(CXX) $(CXXFLAGS) UniquePtrTest.cpp -o t
clean:
	rm t
